<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.2</Version>
  </PropertyGroup>

  <PropertyGroup>
    <Author>keifufu</Author>
    <Name>Facade</Name>
    <Punchline>Change your neighbours' housing exterior appearance.</Punchline>
    <Description>Visually change the exterior appearance of any house so it's no longer an eyesore. (Note: Changes reset upon entering the plot to restore intended collission)</Description>
    <RepoUrl>https://github.com/keifufu/Facade</RepoUrl>
    <IconUrl>https://raw.githubusercontent.com/keifufu/Facade/main/images/icon.png</IconUrl>
    <Tags>facade;housing;exterior</Tags>
  </PropertyGroup>

  <ItemGroup>
   <Content Include="data/plots.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>plots.json</TargetPath>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>
</Project>
